# Generated by Django 5.1.1 on 2024-12-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userpreference_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='link',
            new_name='image_links',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
